services:
  banco_cvm:
    image: postgres:16-alpine
    container_name: banco_cvm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cvm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cvm"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: cvm_api
    environment:
      POSTGRES_HOST: banco_cvm
      POSTGRES_PORT: 5432
      POSTGRES_DB: cvm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "8000:8000"
    depends_on:
      banco_cvm:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    container_name: cvm_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "5500:80"
    depends_on:
      - api

volumes:
  postgres_data: