services:
  banco_cvm:
    image: postgres:16-alpine
    container_name: banco_cvm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cvm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cvm"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: